[package]
name = "lsenext-helper"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
lsenext-core = { path = "../lsenext-core" }
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[features]
diagnostics = []

[[bin]]
name = "lsenext-helper"
path = "src/main.rs"

[[bin]]
name = "lsenext-register"
path = "src/main.rs"

[[bin]]
name = "lsenext-unregister"
path = "src/main.rs"
